[package]
name = "aw16-static-files"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.2"
actix-web = "4.4.0"
regex = "1.10.2"
sanitize-filename = "0.5.0"
